export const menuList=[
    {
        id:1,
        name:'Plain Pratha',
        price:'20',
        url:'',
        imageLink:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD-RegKzxrKhfHvalDNZoep31-Uo4U2Iu7ieHdMgAylA&s',
    },
    {
        id:2,
        name:'Aloo Paratha',
        price:'50',
        url:'',
        imageLink:'https://t3.ftcdn.net/jpg/01/15/62/02/360_F_115620221_5XL4MzVoXrHGJdhHXrVVNL0WUHdJLCPH.jpg',
    },
    {
        id:3,
        name:'Egg Paratha',
        price:'80',
        url:'',
        imageLink:'https://i.ytimg.com/vi/Xz31ahbF9FA/maxresdefault.jpg',
    },
    {
        id:4,
        name:'Paneer Paratha',
        price:'100',
        url:'',
        imageLink:'https://lh5.googleusercontent.com/proxy/OXZYPJIPZvsfIgWz2XGs5FvE5sZC9fk3R65L7BkGrWL7kVBL3ZXKqz1DGnpv0jGO7_GSesLqMxLNEo7DMZ27LIee_r_BHMJkr5dnFA',
    },
    {
        id:5,
        name:'Masala Maggie',
        price:'30',
        url:'',
        imageLink:'https://aartimadan.com/wp-content/uploads/2020/07/Masala-Maggi-Recipe.jpg',
    },
    {
        id:6,
        name:'Veg Maggie',
        price:'40',
        url:'',
        imageLink:'https://i.ytimg.com/vi/T09CbMLq6Wo/maxresdefault.jpg',
    },
    {
        id:7,
        name:'Corn Maggie',
        price:'40',
        url:'',
        imageLink:'https://img-global.cpcdn.com/recipes/550fba81fda6a6cb/680x482cq70/cheese-and-corn-maggi-recipe-main-photo.jpg',
    },
    {
        id:8,
        name:'Veg Cheese Maggie',
        price:'50',
        url:'',
        imageLink:'https://images.aws.nestle.recipes/resized/c1c4418e621bf13cfd28b284cc70db71_Final_Plating_944_531.jpg',
    },
    {
        id:9,
        name:'Aloo Sandwich',
        price:'25',
        url:'',
        imageLink:'https://www.vegrecipesofindia.com/wp-content/uploads/2014/03/aloo-masala-grilled-sandwich-1.jpg',
    },
    {
        id:10,
        name:'Paneer Sandwich',
        price:'35',
        url:'',
        imageLink:'https://greenbowl2soul.com/wp-content/uploads/2022/06/paneer-sandwich-500x500.jpg',
    },
    {
        id:11,
        name:'Egg Roll',
        price:'60',
        url:'',
        imageLink:'https://assets-global.website-files.com/60d34b8627f6e735cf28df18/64907f452e5feec6e20800cf_Egg%20Roll%20Hero%204.3.jpg',
    },
    {
        id:12,
        name:'Paneer Roll',
        price:'80',
        url:'',
        imageLink:'https://ministryofcurry.com/wp-content/uploads/2019/10/kathi-roll_.jpg',
    },
    {
        id:13,
        name:'Egg (Half-Fry)',
        price:'20',
        url:'',
        imageLink:'https://thumbs.dreamstime.com/b/indian-style-tasty-healthy-double-egg-half-fried-omelet-wooden-rustic-background-selective-focus-225790520.jpg',
    },
    {
        id:14,
        name:'Omelette',
        price:'40',
        url:'',
        imageLink:'https://media.istockphoto.com/id/485040276/photo/herb-omelette-with-chives-and-oregano.jpg?s=612x612&w=0&k=20&c=gWzwd_-neHOmCgirxaaGCwEJElbuYPzY917oWPWp6kI=',
    },
    {
        id:15,
        name:'Egg Bhurji',
        price:'40',
        url:'',
        imageLink:'https://spicecravings.com/wp-content/uploads/2023/03/Egg-Bhurji-Featured-1.jpg',
    },
    {
        id:16,
        name:'Cofee',
        price:'20',
        url:'',
        imageLink:'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    },
    {
        id:17,
        name:'Tea',
        price:'15',
        url:'',
        imageLink:'https://www.thestatesman.com/wp-content/uploads/2019/05/tea-culture.jpg',
    },
    {
        id:18,
        name:'Plain Dahi',
        price:'20',
        url:'',
        imageLink:'https://as2.ftcdn.net/v2/jpg/02/25/36/37/1000_F_225363758_HBs0xH8lIYdxU3scFBtydak0Ee5doJWw.jpg',
    },
    {
        id:19,
        name:'Cold Drink',
        price:'MRP',
        url:'',
        imageLink:'https://5.imimg.com/data5/SELLER/Default/2023/3/296872949/ZZ/GG/BW/77999044/cold-drink-recipe-formulation.jpeg',
    },
    {
        id:20,
        name:'Ice Cream',
        price:'MRP',
        url:'',
        imageLink:'https://t4.ftcdn.net/jpg/06/15/69/85/360_F_615698552_jqO2rh2uigkhb8ZLKTmTRLeeBQKtnehC.jpg',
    },
   


    
]